leftnav:
- identifier: d7d4c2b2-3f6f-629a-4073-f609af077054
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 41ec0aca-f666-3c47-8e91-c827e13197f3
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 6731ee2c-8d03-736e-a6f7-edf07ddcb347
  name: Recitations
  pageRef: /pages/recitations
  weight: 30
- identifier: 9bd8adf4-88a3-fc9d-0e9a-4da3fc95bbe9
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
- identifier: a2496f17-8736-2a32-ab1f-41eba1d2ffd3
  name: Projects
  pageRef: /pages/projects
  weight: 50
